export const tiers = [
    {
        name: "BYOK",
        price: "$0",
        eyebrow: "FREE FROM KOE",
        description: "Bring your own Groq key. Koe does not charge you for app usage; provider costs are handled directly by you.",
        features: [
            "Desktop and mobile app access",
            "Use your own Groq API key",
            "Signed-out local processing keeps transcript history on your device",
            "Signed-in account BYOK can store transcript history for future sync",
            "No Koe subscription required",
        ],
        cta: "Download Koe",
        checkoutPlan: null,
        highlighted: false,
    },
    {
        name: "Managed Starter",
        price: "NGN 0",
        eyebrow: "NO API KEY NEEDED",
        description: "For people who just want to sign in and test managed processing before choosing a paid monthly quota.",
        features: [
            "No provider key setup",
            "5 min/day guaranteed when managed free is enabled",
            "Bonus free time while the shared pool is quiet",
            "Server-side processing key stays private",
            "Usage tracked against your account quota",
            "Designed for casual testing",
        ],
        cta: "Create account in app",
        checkoutPlan: null,
        highlighted: false,
    },
    {
        name: "Managed Lite",
        price: "NGN 5,000/mo",
        eyebrow: "CASUAL PAID",
        description: "For light daily dictation without setting up a provider account.",
        features: ["No API key required", "10 hours of managed audio per month", "1,000 managed requests per month", "Account history and usage dashboard"],
        cta: "Open app",
        checkoutPlan: "managed_lite",
        highlighted: false,
    },
    {
        name: "Managed Plus",
        price: "NGN 9,000/mo",
        eyebrow: "BEST VALUE // BEST FIT",
        description: "For regular voice-first writing and everyday cross-app dictation.",
        features: ["No API key required", "25 hours of managed audio per month", "2,500 managed requests per month", "Usage dashboard and account history"],
        cta: "Open app",
        checkoutPlan: "managed_plus",
        highlighted: true,
    },
    {
        name: "Managed Pro",
        price: "NGN 15,000/mo",
        eyebrow: "HEAVIER USE",
        description: "For users who rely on Koe throughout the workday and want a larger cap.",
        features: ["No API key required", "40 hours of managed audio per month", "4,000 managed requests per month", "Usage dashboard and account history"],
        cta: "Open app",
        checkoutPlan: "managed_pro",
        highlighted: false,
    },
];
